### PR TITLE
Use 7.0.x tele to build 5.5.x application

### PR DESCRIPTION
**Pull request by UnderGreen**

### CODE REVIEW

**Comment by wadells** [comment]
The general council I've heard is to avoid a mismatch between the base image and the tele version -- though I don't recall specific bugs offhand.  Why do we want to make this official as part of the jenkins CI?

**Comment by UnderGreen** [comment]
Because Jenkins is used in the infrastructure of M customer.

**Comment by wadells** [comment]
> Because Jenkins is used in the infrastructure of M customer.

My question wasn't about jenkins -- sorry for the mislead!  I am asking about why you're formalizing use of 7.x `tele` binaries to build 5.5 cluster images.  To the best of my knolwege this isn't a use case we support/encourage.  We suggest folks use a 5.5 tele binary to build a 5.5 image.  I ask because I need to update my mental model & guidance if 7.x building 5.x is a good thing.

**Comment by UnderGreen** [comment]
There is an issue with syncer code in gravity 5.5 which prevents building cluster image from a state directory without using an ops center. Difference between 7.0.x code and 5.5.x are so significant and right now I don't have time to look at it and pick only needed changes to patch 5.5.x. I know, it is risky to build with a different version, but from my tests, it is working.

**Comment by wadells** [comment]
> There is an issue with syncer code in gravity 5.5 which prevents building cluster image from a state directory without using an ops center.

Thanks! This is what I was looking for.

**Review by wadells — APPROVED** [review]

**Pull request merged**
