### PR TITLE
Fix app manifest -- node cpu count

### PR DESCRIPTION
**Pull request by alexey-medvedchikov**

### CODE REVIEW

**Comment by sofuture** [comment]
Not sure I understand this, `min_count` refers to number of nodes.

**Comment by alexey-medvedchikov** [comment]
@sofuture sorry, wrong line removed.
This should fix this error, on import:
```Original Error: *errors.errorString failed to validate: installer.servers.node.cpu.min_count: Must be greater than or equal to 1,installer.servers: node: Property "node" does not match pattern "^[a-z0-9_A-Z]+$"```

**Comment by sofuture** [comment]
lgtm

**Comment by sofuture** [comment]
Merged into #31

**Pull request closed without merging**
