### PR TITLE
Disable PITR for now

### PR DESCRIPTION
**Pull request by sofuture**
revert streaming backups for now

### CODE REVIEW

**Comment by sofuture** [comment]
Assigning to you @eldios

**Comment by UnderGreen** [comment]
@sofuture, @eldios 
Guys, what I understood here - main problem with PITR is with the big usage of disk by Pithos.
We can do some cleanup with [backup-list](https://github.com/wal-e/wal-e#backup-list) and [backup-delete](https://github.com/wal-e/wal-e#delete). For example `wal-e delete [--confirm] retain 5` will delete all backups/wals older than last 5 backups.

**Comment by sofuture** [comment]
@UnderGreen yeah, we could add cleanup instead of disabling. Either way is fine with me as long as we're sure that new installs + upgrades both don't use boundless disk.

**Comment by UnderGreen** [comment]
@sofuture, it should be a cron job - for new install and upgrade will work the same way.

**Comment by eldios** [comment]
If we manage to expose that number (eg: `retain 5`) that would be golden as you could tweak it according to specific needs... while retaining the PITR functionality

**Pull request merged**
